version: '3.8'

services:
    jenkins:
        image: jenkins/jenkins:lts
    privileged: true
    user: root
    container_name: jenkins
    volumes:
        - ./jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
    network:
        - sail

networks:
    sail:
        external: true
