version: "3.7"

services:
    db_mysql:
        image: mysql:8.0.28
        restart: always
        container_name: db_mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=local
            - MYSQL_ROOT_PASSWORD=password
            - TZ=Asia/Seoul
        command:
            - --lower_case_table_names=1
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_general_ci
        volumes:
            - ./docker/data:/var/lib/mysql

    phpmyadmin:
        depends_on:
            - db_mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '20080:80'
        environment:
            PMA_HOST: db_mysql
            MYSQL_ROOT_PASSWORD: password
